/*
 * Copyright 2022 Nahuel Gomez https://nahuelwexd.com
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */

#pragma once

#if !defined(_ICU_GOBJECT_INSIDE) && !defined(ICU_GOBJECT_COMPILATION)
#  error "Only <icu-gobject.h> can be included directly"
#endif

#include "icu-version.h"

#define ICU_STANDARD_ERROR (icu_standard_error_quark())
#define ICU_FMT_PARSE_ERROR (icu_fmt_parse_error_quark())

ICU_AVAILABLE_IN_ALL
GQuark icu_standard_error_quark (void) G_GNUC_CONST;

ICU_AVAILABLE_IN_ALL
GQuark icu_fmt_parse_error_quark (void) G_GNUC_CONST;

typedef enum {
  ICU_ILLEGAL_ARGUMENT_ERROR      =  1,
  ICU_MISSING_RESOURCE_ERROR      =  2,
  ICU_INVALID_FORMAT_ERROR        =  3,
  ICU_FILE_ACCESS_ERROR           =  4,
  ICU_INTERNAL_PROGRAM_ERROR      =  5,
  ICU_MESSAGE_PARSE_ERROR         =  6,
  ICU_MEMORY_ALLOCATION_ERROR     =  7,
  ICU_INDEX_OUTOFBOUNDS_ERROR     =  8,
  ICU_PARSE_ERROR                 =  9,
  ICU_INVALID_CHAR_FOUND          = 10,
  ICU_TRUNCATED_CHAR_FOUND        = 11,
  ICU_ILLEGAL_CHAR_FOUND          = 12,
  ICU_INVALID_TABLE_FORMAT        = 13,
  ICU_INVALID_TABLE_FILE          = 14,
  ICU_BUFFER_OVERFLOW_ERROR       = 15,
  ICU_UNSUPPORTED_ERROR           = 16,
  ICU_RESOURCE_TYPE_MISMATCH      = 17,
  ICU_ILLEGAL_ESCAPE_SEQUENCE     = 18,
  ICU_UNSUPPORTED_ESCAPE_SEQUENCE = 19,
  ICU_NO_SPACE_AVAILABLE          = 20,
  ICU_CE_NOT_FOUND_ERROR          = 21,
  ICU_PRIMARY_TOO_LONG_ERROR      = 22,
  ICU_STATE_TOO_OLD_ERROR         = 23,
  ICU_TOO_MANY_ALIASES_ERROR      = 24,
  ICU_ENUM_OUT_OF_SYNC_ERROR      = 25,
  ICU_INVARIANT_CONVERSION_ERROR  = 26,
  ICU_INVALID_STATE_ERROR         = 27,
  ICU_COLLATOR_VERSION_MISMATCH   = 28,
  ICU_USELESS_COLLATOR_ERROR      = 29,
  ICU_NO_WRITE_PERMISSION         = 30,
  ICU_INPUT_TOO_LONG_ERROR        = 31,
} IcuStandardError;

typedef enum {
  ICU_UNEXPECTED_TOKEN = 0x10100,
  ICU_MULTIPLE_DECIMAL_SEPARATORS,
  ICU_MULTIPLE_EXPONENTIAL_SYMBOLS,
  ICU_MALFORMED_EXPONENTIAL_PATTERN,
  ICU_MULTIPLE_PERCENT_SYMBOLS,
  ICU_MULTIPLE_PERMILL_SYMBOLS,
  ICU_MULTIPLE_PAD_SPECIFIERS,
  ICU_PATTERN_SYNTAX_ERROR,
  ICU_ILLEGAL_PAD_POSITION,
  ICU_UNMATCHED_BRACES,
  ICU_UNSUPPORTED_PROPERTY,
  ICU_UNSUPPORTED_ATTRIBUTE,
  ICU_ARGUMENT_TYPE_MISMATCH,
  ICU_DUPLICATE_KEYWORD,
  ICU_UNDEFINED_KEYWORD,
  ICU_DEFAULT_KEYWORD_MISSING,
  ICU_DECIMAL_NUMBER_SYNTAX_ERROR,
  ICU_FORMAT_INEXACT_ERROR,
  ICU_NUMBER_ARG_OUTOFBOUNDS_ERROR,
  ICU_NUMBER_SKELETON_SYNTAX_ERROR,
} IcuFmtParseError;
